# Generated by rust2rpm 28
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate catppuccin-whiskers

Name:           rust-catppuccin-whiskers
Version:        2.9.0
Release:        %autorelease
Summary:        😾 Soothing port creation tool for the high-spirited!

License:        MIT
URL:            https://crates.io/crates/catppuccin-whiskers
Source:         %{crates_source}
Source:         catppuccin-whiskers-2.9.0-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
😾 Soothing port creation tool for the high-spirited!.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CHANGELOG.md
%doc README.md
%{_bindir}/whiskers

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
