[package]
extra-files = [
	"%{bash_completions_dir}/starship",
	"%{fish_completions_dir}/starship.fish",
	"%{zsh_completions_dir}/_starship",
]

[requires]
build = ["git-core"]

[scripts.build]
post = [
	"target/rpm/starship completions bash > starship",
	"target/rpm/starship completions fish > starship.fish",
	"target/rpm/starship completions zsh > _starship",
]

[scripts.install]
post = [
	"install -Dpm 0644 starship -t %{buildroot}%{bash_completions_dir}",
	"install -Dpm 0644 starship.fish -t %{buildroot}%{fish_completions_dir}",
	"install -Dpm 0644 _starship -t %{buildroot}%{zsh_completions_dir}",
]

[tests]
comments = []
