# Generated by rust2rpm 28
%bcond check 1

%global crate bottom

Name:           rust-bottom
Version:        0.14.7
Release:        %autorelease
Summary:        Customizable cross-platform graphical process/system monitor for the terminal

License:        MIT
URL:            https://crates.io/crates/bottom
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          bottom-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A customizable cross-platform graphical process/system monitor for the
terminal. Supports Linux, macOS, and Windows.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# Apache-2.0 OR BSL-1.0
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# BSD-2-Clause OR MIT OR Apache-2.0
# ISC
# MIT
# MIT OR Apache-2.0
# MPL-2.0
# Unlicense OR MIT
# Zlib
# Zlib OR Apache-2.0 OR MIT
License:        %{shrink:
    MIT AND
    (Apache-2.0 OR BSL-1.0) AND
    (Apache-2.0 OR MIT) AND
    (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND
    (BSD-2-Clause OR MIT OR Apache-2.0) AND
    ISC AND
    (MIT OR Apache-2.0) AND
    MPL-2.0 AND
    (Unlicense OR MIT) AND
    Zlib AND
    (Zlib OR Apache-2.0 OR MIT)
}
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc AI_POLICY.md
%doc README.md
%{_bindir}/btm
%{bash_completions_dir}/btm
%{fish_completions_dir}/btm.fish
%{zsh_completions_dir}/_btm
%{_mandir}/man1/btm.1*

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/AI_POLICY.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+battery-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+battery-devel %{_description}

This package contains library source intended for building other packages which
use the "battery" feature of the "%{crate}" crate.

%files       -n %{name}+battery-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deploy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deploy-devel %{_description}

This package contains library source intended for building other packages which
use the "deploy" feature of the "%{crate}" crate.

%files       -n %{name}+deploy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fern-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fern-devel %{_description}

This package contains library source intended for building other packages which
use the "fern" feature of the "%{crate}" crate.

%files       -n %{name}+fern-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+generate_schema-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+generate_schema-devel %{_description}

This package contains library source intended for building other packages which
use the "generate_schema" feature of the "%{crate}" crate.

%files       -n %{name}+generate_schema-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gpu-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gpu-devel %{_description}

This package contains library source intended for building other packages which
use the "gpu" feature of the "%{crate}" crate.

%files       -n %{name}+gpu-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log-devel %{_description}

This package contains library source intended for building other packages which
use the "log" feature of the "%{crate}" crate.

%files       -n %{name}+log-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+logging-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+logging-devel %{_description}

This package contains library source intended for building other packages which
use the "logging" feature of the "%{crate}" crate.

%files       -n %{name}+logging-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nvidia-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nvidia-devel %{_description}

This package contains library source intended for building other packages which
use the "nvidia" feature of the "%{crate}" crate.

%files       -n %{name}+nvidia-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+schemars-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+schemars-devel %{_description}

This package contains library source intended for building other packages which
use the "schemars" feature of the "%{crate}" crate.

%files       -n %{name}+schemars-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+strum-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+strum-devel %{_description}

This package contains library source intended for building other packages which
use the "strum" feature of the "%{crate}" crate.

%files       -n %{name}+strum-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+time-devel %{_description}

This package contains library source intended for building other packages which
use the "time" feature of the "%{crate}" crate.

%files       -n %{name}+time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zfs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zfs-devel %{_description}

This package contains library source intended for building other packages which
use the "zfs" feature of the "%{crate}" crate.

%files       -n %{name}+zfs-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
export BTM_GENERATE=true
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
install -Dpm 0644 target/tmp/bottom/completion/btm.bash \
    %{buildroot}%{bash_completions_dir}/btm
install -Dpm 0644 target/tmp/bottom/completion/btm.fish \
    -t %{buildroot}%{fish_completions_dir}
install -Dpm 0644 target/tmp/bottom/completion/_btm \
    -t %{buildroot}%{zsh_completions_dir}
install -Dpm 0644 target/tmp/bottom/manpage/btm.1 \
    -t %{buildroot}%{_mandir}/man1

%if %{with check}
%check
%cargo_test -- --lib -- --skip collection::tests::test_data_collection
%endif

%changelog
%autochangelog
