# Generated by rust2rpm 28
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate bottom

Name:           rust-bottom
Version:        0.14.8
Release:        %autorelease
Summary:        Customizable cross-platform graphical process/system monitor for the terminal

License:        MIT
URL:            https://crates.io/crates/bottom
Source:         %{crates_source}
Source:         bottom-0.14.8-vendor.tar.xz
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          bottom-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A customizable cross-platform graphical process/system monitor for the
terminal. Supports Linux, macOS, and Windows.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# Apache-2.0 OR BSL-1.0
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# BSD-2-Clause OR MIT OR Apache-2.0
# ISC
# MIT
# MIT OR Apache-2.0
# MPL-2.0
# Unlicense OR MIT
# Zlib
# Zlib OR Apache-2.0 OR MIT
License:        %{shrink:
    MIT AND
    (Apache-2.0 OR BSL-1.0) AND
    (Apache-2.0 OR MIT) AND
    (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND
    (BSD-2-Clause OR MIT OR Apache-2.0) AND
    ISC AND
    (MIT OR Apache-2.0) AND
    MPL-2.0 AND
    (Unlicense OR MIT) AND
    Zlib AND
    (Zlib OR Apache-2.0 OR MIT)
}
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc AI_POLICY.md
%doc README.md
%{_bindir}/btm
%{bash_completions_dir}/btm
%{fish_completions_dir}/btm.fish
%{zsh_completions_dir}/_btm
%{_mandir}/man1/btm.1*

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
export BTM_GENERATE=true
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install
install -Dpm 0644 target/tmp/bottom/completion/btm.bash %{buildroot}%{bash_completions_dir}/btm
install -Dpm 0644 target/tmp/bottom/completion/btm.fish -t %{buildroot}%{fish_completions_dir}
install -Dpm 0644 target/tmp/bottom/completion/_btm -t %{buildroot}%{zsh_completions_dir}
install -Dpm 0644 target/tmp/bottom/manpage/btm.1 -t %{buildroot}%{_mandir}/man1

%if %{with check}
%check
%cargo_test -- --lib -- --skip collection::tests::test_data_collection
%endif

%changelog
%autochangelog
