# Generated by rust2rpm 28
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate zellij

Name:           rust-zellij
Version:        0.44.3
Release:        %autorelease
Summary:        Terminal workspace with batteries included

License:        MIT
URL:            https://crates.io/crates/zellij
Source:         %{crates_source}
Source:         zellij-0.44.3-vendor.tar.xz
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          zellij-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  perl

%global _description %{expand:
A terminal workspace with batteries included.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.md
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/zellij
%{bash_completions_dir}/zellij
%{fish_completions_dir}/zellij.fish
%{zsh_completions_dir}/_zellij

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}
target/rpm/zellij setup --generate-completion bash > zellij
target/rpm/zellij setup --generate-completion fish > zellij.fish
target/rpm/zellij setup --generate-completion zsh > _zellij

%install
%cargo_install
install -Dpm 0644 zellij -t %{buildroot}%{bash_completions_dir}
install -Dpm 0644 zellij.fish -t %{buildroot}%{fish_completions_dir}
install -Dpm 0644 _zellij -t %{buildroot}%{zsh_completions_dir}

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
