[package]
extra-files = [
	"%{bash_completions_dir}/zellij",
	"%{fish_completions_dir}/zellij.fish",
	"%{zsh_completions_dir}/_zellij",
]

[requires]
build = ["perl"]

[scripts.build]
post = [
	"target/rpm/zellij setup --generate-completion bash > zellij",
	"target/rpm/zellij setup --generate-completion fish > zellij.fish",
	"target/rpm/zellij setup --generate-completion zsh > _zellij",
]

[scripts.install]
post = [
	"install -Dpm 0644 zellij -t %{buildroot}%{bash_completions_dir}",
	"install -Dpm 0644 zellij.fish -t %{buildroot}%{fish_completions_dir}",
	"install -Dpm 0644 _zellij -t %{buildroot}%{zsh_completions_dir}",
]

[tests]
comments = []
