#!/bin/bash
echo "🔐 GitHub Secrets Setup"
echo ""
echo "1. Go to: https://copr.fedorainfracloud.org/api/"
echo "   Copy: username, login, token"
echo ""
echo "2. In GitHub repo:"
echo "   Settings → Secrets and variables → Actions → New secret"
echo ""
echo "3. Add these 4 secrets:"
echo "   COPR_USERNAME   = (your username)"
echo "   COPR_LOGIN      = (login token)"
echo "   COPR_TOKEN      = (token)"
echo "   COPR_REPO       = (username/repo-name)"
echo ""
echo "⚠️  Never commit credentials to the repository"
