#!/bin/bash
echo "🔗 COPR Webhook Setup"
echo ""
echo "1. Get from COPR: Settings → Integrations → Webhooks"
echo ""
echo "2. Format:"
echo "   GitHub:  https://copr.fedorainfracloud.org/webhooks/github/<PROJECT_ID>/<TOKEN>/"
echo "   GitLab:  https://copr.fedorainfracloud.org/webhooks/gitlab/<PROJECT_ID>/<TOKEN>/"
echo ""
echo "3. Add to GitHub/GitLab: Settings → Webhooks → Add webhook"
echo ""
echo "See WEBHOOK-SETUP.md for details"
