name: Sync Package Versions

on:
  schedule:
    - cron: '*/5 * * * *'
      timezone: 'Asia/Jakarta'
  workflow_dispatch:

concurrency:
  group: sync-packages
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    permissions:
      contents: write

    steps:
      - name: Install System Dependencies
        run: |
          dnf install -y git python3 rust2rpm

      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run Sync Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 scripts/sync.py

      - name: Commit and Push Changes
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, creating commit..."

            git add .
            git commit -m "chore(sync): auto-update package versions and spec files [skip ci]"

            git pull --rebase origin main
            git push
          else
            echo "No package updates found. Repository is up to date."
          fi
